version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  mongo:
        image: mongo:latest
        volumes:
          - data:/data
        deploy:
            restart_policy:
                condition: always
        ports:
            - "27017:27017"
volumes:
  data:
